name: Shycat CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/maven.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Spring Boot Application
      run: mvn -B package --file backend/pom.xml

    - name: Prepare Deployment Package
      run: |
        mkdir -p deploy
        cp backend/target/*.jar deploy/app.jar

    - name: Upload Application to EC2
      uses: appleboy/scp-action@v0.2.5
      with:
        host: ${{ secrets.SHYCAT_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SHYCAT_EC2_SSH_KEY }}
        source: deploy/app.jar
        target: /opt/shycat/app.jar

    - name: Restart Application on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SHYCAT_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SHYCAT_EC2_SSH_KEY }}
        script: |
          sudo systemctl restart shycat.service
